import express from 'express';
import crypto from 'crypto';
import { createUser, authenticateUser, getSession, ensureOwnerUser, saveBookmakerToken, saveBookmakerCredentials, listBookmakerConnections, getBookmakerConnection, setBookmakerAutoBet, deleteBookmakerConnection, recordConnectionEvent, dbStatus } from './db/index.js';
import { listExecutionHistory, historyStatus } from './history-store.js';
import { executionStrategy } from './execution-strategies.js';
import { autoStakeStatus, setAutoStake, assertAutoStakeAllowed, clearAutoStake } from './auto-stake.js';
import { generateCoupon, rankPredictions, pronoEngineStatus } from './prono-engine.js';
import { pronoProductStatus, validateAutoWindow, validateManualHorizon } from './prono-config.js';

const router=express.Router();
const BOOKMAKERS=['sportybet','betmomo','premierbet','betpawa.cm','1xbet','1xwin','afropari','betclic','yellowbet','22bet','pmuc','supergooal','betwinner','melbet','bettomax','paripesa','onebet','betsson'];
const CHANNELS=['official_api','user_credentials','user_token','partner_sdk','browser_rpa','android_rpa','deeplink_coupon','authorized_gateway'];
const OWNER_CODE=String(process.env.OWNER_CODE||'').trim().toUpperCase();
const OWNER_SALT=String(process.env.OWNER_CODE_SALT||'deck-pro-owner-v1');
const OWNER_HASH=String(process.env.OWNER_CODE_HASH||'').trim().toLowerCase();
const OWNER_SECRET=String(process.env.OWNER_TOKEN_SECRET||'').trim();
const EFFECTIVE_HASH=OWNER_CODE?crypto.createHash('sha256').update(OWNER_SALT+OWNER_CODE).digest('hex'):(OWNER_HASH||'');
const EFFECTIVE_SECRET=OWNER_SECRET||(EFFECTIVE_HASH?crypto.createHash('sha256').update('deck-pro-token-v1'+EFFECTIVE_HASH).digest('hex'):'');
const OWNER_CONFIG_SOURCE=OWNER_CODE?'OWNER_CODE':(OWNER_HASH?'OWNER_CODE_HASH':'NONE');
console.info(`[Deck Pro owner-auth] configured=${Boolean(EFFECTIVE_HASH&&EFFECTIVE_SECRET)} source=${OWNER_CONFIG_SOURCE} codePresent=${Boolean(OWNER_CODE)} hashPresent=${Boolean(OWNER_HASH)} saltCustom=${Boolean(process.env.OWNER_CODE_SALT)} secretCustom=${Boolean(OWNER_SECRET)}`);
function bearer(req){return String(req.headers.authorization||'').replace(/^Bearer\s+/i,'').trim()}
function ownerIdentity(raw){try{if(!EFFECTIVE_SECRET||!raw)return null;const [p,s]=String(raw).split('.');if(!p||!s)return null;const expected=crypto.createHmac('sha256',EFFECTIVE_SECRET).update(p).digest('base64url');if(s!==expected)return null;const payload=JSON.parse(Buffer.from(p,'base64url').toString());if(payload.role!=='owner'||Number(payload.exp)<=Date.now())return null;return payload}catch{return null}}
function ownerToken(device=''){const p=Buffer.from(JSON.stringify({role:'owner',exp:Date.now()+2592000000,did:device})).toString('base64url');return p+'.'+crypto.createHmac('sha256',EFFECTIVE_SECRET).update(p).digest('base64url')}
async function userAuth(req,res,next){try{const raw=bearer(req);const session=await getSession(raw);if(session){req.user=session;return next()}const owner=ownerIdentity(raw);if(owner){const ownerKey=EFFECTIVE_HASH||crypto.createHash('sha256').update(OWNER_SALT+String(owner.did||'owner')).digest('hex');const user=await ensureOwnerUser(ownerKey);req.user={user_id:user.id,username:user.username,expires_at:new Date(Date.now()+3600000)};return next()}return res.status(401).json({ok:false,error:'Session utilisateur invalide ou expirée.',code:'USER_SESSION_INVALID'})}catch(e){return res.status(e?.status||503).json({ok:false,error:e?.message||'Base de données indisponible.',code:e?.code||'DATABASE_ERROR'})}}
function fail(res,e){return res.status(e?.status||503).json({ok:false,error:e?.message||'Erreur serveur.',code:e?.code||'ACCOUNT_API_ERROR'})}
function connectionView(row){const strategy=executionStrategy(row.bookmaker_slug);return{...row,hasCredentials:true,execution:{preferred:strategy?.preferred||null,channels:strategy?.channels||{},executionEnabled:Boolean(strategy?.preferred&&strategy?.channels?.[strategy.preferred]?.enabled&&strategy?.channels?.[strategy.preferred]?.verified)}}}
router.post('/api/activate',(req,res)=>{const code=String(req.body?.code||'').trim().toUpperCase();const deviceId=String(req.body?.deviceId||'').trim().slice(0,160);if(!EFFECTIVE_HASH||!EFFECTIVE_SECRET)return res.status(503).json({ok:false,error:'Activation propriétaire non configurée.',code:'OWNER_ACTIVATION_NOT_CONFIGURED'});const submittedHash=crypto.createHash('sha256').update(OWNER_SALT+code).digest('hex');if(!/^\d{4}$/.test(code)||submittedHash!==EFFECTIVE_HASH){console.warn(`[Deck Pro owner-auth] activation rejected: formatOk=${/^\d{4}$/.test(code)} source=${OWNER_CONFIG_SOURCE} effectiveHashPresent=${Boolean(EFFECTIVE_HASH)} effectiveSecretPresent=${Boolean(EFFECTIVE_SECRET)}`);return res.status(401).json({ok:false,error:'Code propriétaire incorrect.',code:'OWNER_CODE_INVALID'});}if(!deviceId)return res.status(400).json({ok:false,error:'Identifiant appareil requis.',code:'DEVICE_ID_REQUIRED'});res.setHeader('Cache-Control','no-store');return res.json({ok:true,role:'owner',deviceId,token:ownerToken(deviceId)})});
router.get('/api/account/status',(req,res)=>res.json({ok:true,db:dbStatus(),history:historyStatus(),bookmakers:BOOKMAKERS,prono:pronoEngineStatus(),product:pronoProductStatus()}));
router.post('/api/account/register',async(req,res)=>{try{const username=String(req.body?.username||'').trim().toLowerCase(),code=String(req.body?.code||'').trim();if(!/^[a-z0-9_.-]{3,40}$/.test(username))return res.status(400).json({ok:false,error:'Nom utilisateur invalide.',code:'USERNAME_INVALID'});if(!/^\d{4}$/.test(code))return res.status(400).json({ok:false,error:'Le code utilisateur doit contenir exactement 4 chiffres.',code:'CODE_INVALID'});const user=await createUser(username,code);res.status(201).json({ok:true,user:{id:user.id,username:user.username}})}catch(e){fail(res,e)}});
router.post('/api/account/login',async(req,res)=>{try{const username=String(req.body?.username||'').trim().toLowerCase(),code=String(req.body?.code||'').trim(),deviceId=String(req.body?.deviceId||'').trim().slice(0,160);if(!username||!/^\d{4}$/.test(code))return res.status(400).json({ok:false,error:'Identifiants invalides.',code:'LOGIN_INVALID'});const result=await authenticateUser(username,code,deviceId||'unknown');if(!result)return res.status(401).json({ok:false,error:'Nom utilisateur ou code incorrect.',code:'LOGIN_FAILED'});res.json({ok:true,token:result.token,expiresAt:result.expiresAt,user:{id:result.user.id,username:result.user.username}})}catch(e){fail(res,e)}});
router.get('/api/account/me',userAuth,(req,res)=>res.json({ok:true,user:{id:req.user.user_id,username:req.user.username},expiresAt:req.user.expires_at}));
router.get('/api/account/history',userAuth,async(req,res)=>{try{const limit=Math.min(Math.max(Number(req.query.limit)||50,1),200);res.json({ok:true,persistent:historyStatus().persistent,history:await listExecutionHistory({userId:req.user.user_id,limit})})}catch(e){fail(res,e)}});
router.get('/api/account/bookmakers',userAuth,async(req,res)=>{try{res.json({ok:true,bookmakers:(await listBookmakerConnections(req.user.user_id)).map(connectionView)})}catch(e){fail(res,e)}});
router.post('/api/account/bookmakers/:slug/connect',userAuth,async(req,res)=>{try{const slug=String(req.params.slug||'').trim().toLowerCase(),channel=String(req.body?.channel||'user_credentials').trim().toLowerCase(),accountLabel=String(req.body?.accountLabel||'').trim().slice(0,120),syncSecret=String(req.body?.syncSecret||'').trim();if(!BOOKMAKERS.includes(slug))return res.status(404).json({ok:false,error:'Bookmaker non supporté.',code:'BOOKMAKER_UNSUPPORTED'});if(!CHANNELS.includes(channel))return res.status(400).json({ok:false,error:'Canal de connexion non supporté.',code:'CHANNEL_UNSUPPORTED'});if(!accountLabel)return res.status(400).json({ok:false,error:'Nom du compte requis pour permettre plusieurs comptes du même bookmaker.',code:'ACCOUNT_LABEL_REQUIRED'});const credentials=req.body?.credentials&&typeof req.body.credentials==='object'?req.body.credentials:{};const saved=await saveBookmakerCredentials(req.user.user_id,slug,channel,credentials,accountLabel,syncSecret);await recordConnectionEvent(req.user.user_id,slug,'credentials_saved',true,{channel,accountLabel});res.status(201).json({ok:true,connection:connectionView(saved),message:'Identifiants chiffrés et synchronisation enregistrée. La mise automatique reste inactive tant que le canal de placement réel n\'est pas vérifié.'})}catch(e){fail(res,e)}});
router.post('/api/account/bookmakers/:slug/token',userAuth,async(req,res)=>{try{const slug=String(req.params.slug||'').trim().toLowerCase(),channel=String(req.body?.channel||'user_token').trim().toLowerCase(),token=String(req.body?.token||'').trim(),accountLabel=String(req.body?.accountLabel||'').trim().slice(0,120);if(!BOOKMAKERS.includes(slug))return res.status(404).json({ok:false,error:'Bookmaker non supporté.',code:'BOOKMAKER_UNSUPPORTED'});if(!CHANNELS.includes(channel))return res.status(400).json({ok:false,error:'Canal de connexion non supporté.',code:'CHANNEL_UNSUPPORTED'});if(!token)return res.status(400).json({ok:false,error:'Token bookmaker requis.',code:'BOOKMAKER_TOKEN_REQUIRED'});if(!accountLabel)return res.status(400).json({ok:false,error:'Nom du compte requis.',code:'ACCOUNT_LABEL_REQUIRED'});const saved=await saveBookmakerToken(req.user.user_id,slug,channel,token,accountLabel);await recordConnectionEvent(req.user.user_id,slug,'token_saved',true,{channel,accountLabel});res.status(201).json({ok:true,connection:connectionView(saved)})}catch(e){fail(res,e)}});
router.post('/api/account/bookmakers/connection/:id/auto-bet',userAuth,async(req,res)=>{try{const result=await setBookmakerAutoBet(req.user.user_id,String(req.params.id),req.body?.enabled===true);if(!result)return res.status(404).json({ok:false,error:'Compte bookmaker introuvable.',code:'CONNECTION_NOT_FOUND'});await recordConnectionEvent(req.user.user_id,result.bookmaker_slug,result.auto_bet_enabled?'auto_bet_enabled':'auto_bet_disabled',true,{connectionId:result.id});res.json({ok:true,connection:result})}catch(e){fail(res,e)}});
router.delete('/api/account/bookmakers/connection/:id',userAuth,async(req,res)=>{try{const result=await deleteBookmakerConnection(req.user.user_id,String(req.params.id));if(!result)return res.status(404).json({ok:false,error:'Compte bookmaker introuvable.',code:'CONNECTION_NOT_FOUND'});await recordConnectionEvent(req.user.user_id,result.bookmaker_slug,'connection_deleted',true,{connectionId:result.id});res.json({ok:true,deleted:result})}catch(e){fail(res,e)}});
router.post('/api/account/bookmakers/connection/:id/sync-check',userAuth,async(req,res)=>{try{const connection=await getBookmakerConnection(req.user.user_id,String(req.params.id));if(!connection)return res.status(404).json({ok:false,error:'Compte bookmaker introuvable.',code:'CONNECTION_NOT_FOUND'});const hasSecret=Boolean(connection.sync_secret_hash);const hasCredentials=Boolean(connection.credentials||connection.token);res.status(hasCredentials?200:422).json({ok:hasCredentials,connection:{id:connection.id,bookmaker_slug:connection.bookmaker_slug,account_label:connection.account_label,status:connection.status,hasCredentials,hasSyncSecret:hasSecret,autoBetEnabled:connection.auto_bet_enabled},message:hasCredentials?'Accès enregistré. Une validation de connexion réelle dépend du canal du bookmaker.':'Aucun identifiant exploitable enregistré.'})}catch(e){fail(res,e)}});
router.get('/api/account/auto-stake',userAuth,(req,res)=>res.json({ok:true,autoStake:autoStakeStatus(req.user.user_id)}));
router.post('/api/account/auto-stake',userAuth,async(req,res)=>{try{const result=setAutoStake(req.user.user_id,{enabled:req.body?.enabled,confirmationId:String(req.body?.confirmationId||'').trim(),reason:'user_action'});if(!result.ok)return res.status(422).json(result);await recordConnectionEvent(req.user.user_id,'system',req.body?.enabled?'auto_stake_enabled':'auto_stake_disabled',true,{expiresAt:result.state.expiresAt});res.json(result)}catch(e){fail(res,e)}});
router.post('/api/account/auto-stake/authorize',userAuth,(req,res)=>{const result=assertAutoStakeAllowed(req.user.user_id);res.status(result.ok?200:403).json(result)});
router.get('/api/account/prono/status',userAuth,(req,res)=>res.json({ok:true,engine:pronoEngineStatus(),product:pronoProductStatus()}));
router.post('/api/account/prono/rank',userAuth,(req,res)=>{try{const predictions=Array.isArray(req.body?.predictions)?req.body.predictions:[];res.json({ok:true,predictions:rankPredictions(predictions)})}catch(e){fail(res,e)}});
router.post('/api/account/prono/coupon',userAuth,(req,res)=>{try{const body=req.body||{};const maxSelections=Math.min(Math.max(Number(body.maxSelections)||50,1),50);const result=generateCoupon({predictions:Array.isArray(body.predictions)?body.predictions:[],maxSelections,minOdds:body.minOdds,maxOdds:body.maxOdds,bookmaker:body.bookmaker});res.json(result)}catch(e){fail(res,e)}});
router.get('/api/account/product-config',userAuth,(req,res)=>res.json({ok:true,...pronoProductStatus()}));
router.post('/api/account/area-window',userAuth,(req,res)=>{const area=req.body?.area;const mode=String(req.body?.mode||'auto').toLowerCase();const result=mode==='manual'?validateManualHorizon({area,days:req.body?.days}):validateAutoWindow({area,days:req.body?.days});res.status(result.ok?200:422).json(result)});
router.post('/api/account/logout',userAuth,async(req,res)=>{try{clearAutoStake(req.user.user_id,'logout');await recordConnectionEvent(req.user.user_id,'system','logout',true,{});res.json({ok:true})}catch(e){fail(res,e)}});
export { userAuth };
export default router;
