import pg from 'pg';
const { Pool } = pg;
const DATABASE_URL=String(process.env.DATABASE_URL||'').trim();
const pool=DATABASE_URL?new Pool({connectionString:DATABASE_URL,ssl:process.env.DATABASE_SSL==='false'?false:{rejectUnauthorized:false},max:Number(process.env.DB_POOL_MAX||10)}):null;
export function historyStatus(){return{configured:Boolean(pool),persistent:Boolean(pool)}}
export async function ensureHistoryStore(){if(!pool)return false;await pool.query(`CREATE TABLE IF NOT EXISTS execution_history (id BIGSERIAL PRIMARY KEY,transaction_id TEXT,idempotency_key TEXT,user_id UUID,request_id TEXT,event_type TEXT NOT NULL,status TEXT,decision TEXT,decision_code TEXT,accepted_legs INTEGER NOT NULL DEFAULT 0,total_legs INTEGER NOT NULL DEFAULT 0,payload JSONB NOT NULL DEFAULT '{}'::jsonb,created_at TIMESTAMPTZ NOT NULL DEFAULT now());CREATE INDEX IF NOT EXISTS execution_history_user_idx ON execution_history(user_id,created_at DESC);CREATE INDEX IF NOT EXISTS execution_history_idempotency_idx ON execution_history(idempotency_key,created_at DESC);CREATE INDEX IF NOT EXISTS execution_history_created_idx ON execution_history(created_at DESC);`);return true}
export async function recordExecutionHistory(event={}){if(!pool)return false;await pool.query(`INSERT INTO execution_history(transaction_id,idempotency_key,user_id,request_id,event_type,status,decision,decision_code,accepted_legs,total_legs,payload) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)`,[event.transactionId||null,event.idempotencyKey||null,event.userId||null,event.requestId||null,event.eventType||'execution_event',event.status||null,event.decision||null,event.decisionCode||null,Number(event.acceptedLegs||0),Number(event.totalLegs||0),JSON.stringify(event.payload||{})]);return true}
export async function listExecutionHistory({userId=null,limit=50}={}){if(!pool)return[];const safeLimit=Math.min(Math.max(Number(limit)||50,1),200);const r=userId?await pool.query(`SELECT id,transaction_id,idempotency_key,request_id,event_type,status,decision,decision_code,accepted_legs,total_legs,payload,created_at FROM execution_history WHERE user_id=$1 ORDER BY created_at DESC LIMIT $2`,[userId,safeLimit]):await pool.query(`SELECT id,transaction_id,idempotency_key,request_id,event_type,status,decision,decision_code,accepted_legs,total_legs,payload,created_at FROM execution_history ORDER BY created_at DESC LIMIT $1`,[safeLimit]);return r.rows}
export async function closeHistoryStore(){if(pool)await pool.end()}
