import test from 'node:test';
import assert from 'node:assert/strict';
import { decideExecution } from './decision-engine.js';
import { executeTwoLegTransaction, getExecutionTransaction } from './execution-engine.js';
import { setAutoStake, clearAutoStake } from './auto-stake.js';

const radarOpportunity={eventId:'radar-event-1',market:'winner',expiresAt:Date.now()+60000,legs:[
 {bookmaker:'sportybet',selection:'A',outcome:'A',price:2.10,expectedOdds:2.10,eventId:'radar-event-1',market:'winner',stake:1500,channel:'official_api'},
 {bookmaker:'1xbet',selection:'B',outcome:'B',price:2.10,expectedOdds:2.10,eventId:'radar-event-1',market:'winner',stake:1500,channel:'official_api'}
]};

test('Radar -> decision -> confirmation -> execution: confirmed decision reaches preflight',async()=>{const userId='radar-flow-confirmed',key=`radar-confirmed-${Date.now()}`;clearAutoStake(userId);setAutoStake(userId,{enabled:true,confirmationId:'confirmation-radar-1'});const decision=decideExecution({userAuthenticated:true,userId,autoStakeEnabled:true,confirmationValid:true,pairValid:true,executionReady:true,legs:radarOpportunity.legs,expiresAt:radarOpportunity.expiresAt});assert.equal(decision.decision,'CONFIRMED');const result=await executeTwoLegTransaction({legs:radarOpportunity.legs,idempotencyKey:key,userId,autoStake:true,decisionContext:{userAuthenticated:true,autoStakeEnabled:true,confirmationValid:true,pairValid:true,executionReady:true,expiresAt:radarOpportunity.expiresAt}});assert.equal(result.stage,'preflight');assert.equal(result.decision,'CONFIRMED');assert.equal(result.code,'PREFLIGHT_FAILED');assert.equal(getExecutionTransaction(key),null);clearAutoStake(userId)});

test('Radar -> refusal: changed odds stop before execution',()=>{const userId='radar-flow-odds-refused';clearAutoStake(userId);setAutoStake(userId,{enabled:true,confirmationId:'confirmation-radar-2'});const legs=radarOpportunity.legs.map((leg,index)=>index===0?{...leg,currentPrice:2.00}:leg);const decision=decideExecution({userAuthenticated:true,userId,autoStakeEnabled:true,confirmationValid:true,pairValid:true,executionReady:true,legs,expiresAt:radarOpportunity.expiresAt});assert.equal(decision.decision,'REFUSED');assert.equal(decision.code,'ODDS_CHANGED');clearAutoStake(userId)});

test('Radar -> refusal: expired opportunity cannot be confirmed',()=>{const userId='radar-flow-expired';clearAutoStake(userId);setAutoStake(userId,{enabled:true,confirmationId:'confirmation-radar-3'});const decision=decideExecution({userAuthenticated:true,userId,autoStakeEnabled:true,confirmationValid:true,pairValid:true,executionReady:true,legs:radarOpportunity.legs,expiresAt:1000,now:1001});assert.equal(decision.decision,'REFUSED');assert.equal(decision.code,'EXPIRED');clearAutoStake(userId)});

test('Radar -> refusal: disabled Mise Auto blocks automatic execution',async()=>{const userId='radar-flow-auto-disabled',key=`radar-disabled-${Date.now()}`;clearAutoStake(userId);const decision=decideExecution({userAuthenticated:true,userId,autoStakeEnabled:true,confirmationValid:true,pairValid:true,executionReady:true,legs:radarOpportunity.legs});assert.equal(decision.decision,'REFUSED');assert.equal(decision.code,'AUTO_STAKE_BLOCKED');const result=await executeTwoLegTransaction({legs:radarOpportunity.legs,idempotencyKey:key,userId,autoStake:true,decisionContext:{userAuthenticated:true,autoStakeEnabled:true,confirmationValid:true,pairValid:true,executionReady:true}});assert.equal(result.ok,false);assert.equal(result.code,'AUTO_STAKE_DISABLED');assert.equal(getExecutionTransaction(key),null)});

test('Radar -> execution remains fail-closed when bookmaker route is not verified',async()=>{const userId='radar-flow-no-route',key=`radar-no-route-${Date.now()}`;clearAutoStake(userId);setAutoStake(userId,{enabled:true,confirmationId:'confirmation-radar-4'});const result=await executeTwoLegTransaction({legs:radarOpportunity.legs,idempotencyKey:key,userId,autoStake:true,decisionContext:{userAuthenticated:true,autoStakeEnabled:true,confirmationValid:true,pairValid:true,executionReady:true}});assert.equal(result.ok,false);assert.equal(result.stage,'preflight');assert.equal(result.code,'PREFLIGHT_FAILED');clearAutoStake(userId)});
